### ISSUE TITLE
Dealing with status 403

### ISSUE THREAD

**Issue by RobinD42** [xrav3nz/discourse-wellfed#5]
I've set up an RSS feed from a gmail label using this: https://mashe.hawksey.info/2013/05/gmail-label-to-rss-feed/
which appears to be working correctly with a RSS feed reader tool. But when I try to use it with wellfed I have errors like the following showing up in the discourse log. Any ideas?

```
default: FinalDestination could not resolve URL (status 403): https://script.google.com/macros/s/AKfycbwYa98BdPdiWldqfz_k88LpqzW6zDMBxGCr8HaH8M0a9P3cU6M/exec?feedId=6e0bf926-fc74-432e-a248-fba298e3baee

/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/logster-2.3.1/lib/logster/logger.rb:110:in `report_to_store'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/logster-2.3.1/lib/logster/logger.rb:101:in `add_with_opts'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/logster-2.3.1/lib/logster/logger.rb:52:in `add'
/usr/local/lib/ruby/2.6.0/logger.rb:534:in `warn'
/var/www/discourse/lib/final_destination.rb:330:in `public_send'
/var/www/discourse/lib/final_destination.rb:330:in `log'
/var/www/discourse/lib/final_destination.rb:256:in `resolve'
/var/www/discourse/lib/final_destination.rb:249:in `resolve'
/var/www/discourse/app/jobs/scheduled/poll_feed.rb:112:in `fetch_rss'
/var/www/discourse/app/jobs/scheduled/poll_feed.rb:93:in `parsed_feed'
/var/www/discourse/app/jobs/scheduled/poll_feed.rb:79:in `topics'
/var/www/discourse/app/jobs/scheduled/poll_feed.rb:33:in `poll_feed'
/var/www/discourse/app/jobs/scheduled/poll_feed.rb:20:in `execute'
/var/www/discourse/app/jobs/base.rb:232:in `block (2 levels) in perform'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/rails_multisite-2.0.7/lib/rails_multisite/connection_management.rb:63:in `with_connection'
/var/www/discourse/app/jobs/base.rb:221:in `block in perform'
/var/www/discourse/app/jobs/base.rb:217:in `each'
/var/www/discourse/app/jobs/base.rb:217:in `perform'
/var/www/discourse/app/jobs/base.rb:279:in `perform'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/mini_scheduler-0.11.0/lib/mini_scheduler/manager.rb:83:in `process_queue'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/mini_scheduler-0.11.0/lib/mini_scheduler/manager.rb:34:in `block in initialize'
```

**Comment by RobinD42** [comment]
There are some other errors in the log that are related. They look like this:

```
Job exception: no implicit conversion of nil into String

/usr/local/lib/ruby/2.6.0/rss/parser.rb:123:in `readable?'
/usr/local/lib/ruby/2.6.0/rss/parser.rb:123:in `normalize_rss'
/usr/local/lib/ruby/2.6.0/rss/parser.rb:108:in `initialize'
/usr/local/lib/ruby/2.6.0/rss/parser.rb:85:in `new'
/usr/local/lib/ruby/2.6.0/rss/parser.rb:85:in `parse'
/var/www/discourse/plugins/discourse-wellfed/app/jobs/discourse_wellfed/poll_feed.rb:34:in `topics_polled_from_feed'
/var/www/discourse/plugins/discourse-wellfed/app/jobs/discourse_wellfed/poll_feed.rb:28:in `poll_feed'
/var/www/discourse/plugins/discourse-wellfed/app/jobs/discourse_wellfed/poll_feed.rb:12:in `execute'
/var/www/discourse/app/jobs/base.rb:232:in `block (2 levels) in perform'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/rails_multisite-2.0.7/lib/rails_multisite/connection_management.rb:63:in `with_connection'
/var/www/discourse/app/jobs/base.rb:221:in `block in perform'
/var/www/discourse/app/jobs/base.rb:217:in `each'
/var/www/discourse/app/jobs/base.rb:217:in `perform'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:192:in `execute_job'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:165:in `block (2 levels) in process'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/var/www/discourse/lib/sidekiq/pausable.rb:138:in `call'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:164:in `block in process'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/job_retry.rb:109:in `local'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq.rb:37:in `block in <module:Sidekiq>'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:250:in `stats'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/job_logger.rb:8:in `call'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/job_retry.rb:74:in `global'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:125:in `block in dispatch'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/logging.rb:48:in `with_context'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:124:in `dispatch'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:163:in `process'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:83:in `process_one'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:71:in `run'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/util.rb:16:in `watchdog'
/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by xrav3nz** [comment]
Hi @RobinD42, thanks for checking out the plugin. I can't think of anything off the top of my mind, especially that it worked for an RSS reader. 

Also, I don't think this is a Wellfed-specific issue, as it is also failing in Discourse core (from your first backtrace):

```
...
/var/www/discourse/lib/final_destination.rb:256:in `resolve'
/var/www/discourse/lib/final_destination.rb:249:in `resolve'
/var/www/discourse/app/jobs/scheduled/poll_feed.rb:112:in `fetch_rss'
...
```

You many want to create a topic on http://meta.discourse.org.

**Comment by RobinD42** [comment]
Hi @xrav3nz. Yes, noticed that too and I discovered earlier today that the errors were due to "Import posts via RSS/Atom" being turned on in Customize>Embedding. I turned that off and now there are no more manifestations of those errors. However I'm still not getting posts from the RSS loaded into the designated category, and there's no new item in the discourse log to give me any clues why.

I made a local copy of the current state of the feed and put it on one of my other servers, and changed the wellfed config to use that URL. I can see in that server's logs that the file is being fetched every 10 minutes, but still nothing is showing up in the category. I have another feed from a different source that is working as expected, but this one isn't. If you have time to look at it, the static test file is at https://riobu.com/wxPython-github.xml. Maybe it has something in the XML that is tripping up your plugin? My Ruby experience is almost nil, so at this point I'm still basically just poking a blob of unknown substance with sticks, and not getting very far.

**Comment by xrav3nz** [comment]
Thanks for the details and the test file; they made debugging tremendously easier!

The plugin wasn't reading the `<summary>` ATOM element for content before, https://github.com/xrav3nz/discourse-wellfed/commit/46b749f0bc139d177480479bf6348337c45dcf50 should fix this issue.
